# Generated by Django 5.2.4 on 2025-07-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cart_item_cartitem_alter_cart_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quentity',
            field=models.IntegerField(),
        ),
    ]
